### ISSUE TITLE
Feature Request: Multilingual Installer / at least in English

### ISSUE THREAD

**Issue by tapwag** [pwafzig/bilddatenbank#11]
At present the installer language seems only to be in German. As I am planning to also bring my former employer lmkmedia.com into this project and Werner also has some contacts to Italy as well we should think about adding English language to the installer.

**Comment by pwafzig** [comment]
Hi,

i need to refactor the installer since i figured out various problems with it. Will include an english version for the time being until there's something internationalized like you suggested in #12 - should be fine for most people.

Best
Peter

**Comment by pwafzig** [comment]
Hi @tapwag - this one has been fixed with #13, installer is now in english 👍
