### ISSUE TITLE
Installer Breaks in fresh install - Make config.inc.php writeable by default

### ISSUE THREAD

**Issue by tapwag** [pwafzig/bilddatenbank#4]
Hello everyone,

I am currently trying out the master-branch which I cloned it into my XAMPP htdocs directory on macOS Ventura with a release of PHP 8.2 built into XAMPP.

Expected Behavior: Installer should continue the installation or at least include some information on how to make the file config.inc.php writeable.

I was able to fix this using the commandline

`chmod a+w config.inc.php`

in the base "bilddatenbank" directory.

I am not sure how github.com handles permissions but this might be a first breaking point for some users.

**Comment by pwafzig** [comment]
Hi @tapwag - i will close this one as well - the installer now checks for directories and not files. Done in #13 👍
